# Generated by Django 4.2.30 on 2026-06-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_alter_studentprofile_experience_years'),
        ('jobs', '__first__'),
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(help_text='e.g. 12 LPA', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Decision'), ('ACCEPTED', 'Offer Accepted'), ('REJECTED', 'Offer Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_letter_text', models.TextField(default='Dear candidate, We are pleased to extend this trainer selection offer letter for the selected role parameters. Welcome aboard!', help_text='Full contents of selection offer letter')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.recruiterprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('TESTING', 'Online Assessment Stage'), ('INTERVIEWING', 'Interview Scheduled'), ('OFFER_EXTENDED', 'Selected'), ('OFFER_ACCEPTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('screener_score', models.IntegerField(default=60, help_text='AI-estimated skills screening rank score out of 100')),
                ('feedback_notes', models.TextField(blank=True, help_text='Notes from corporate recruiter audit', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='trainees.resume')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'job')},
            },
        ),
    ]
