# Generated by Django 4.2.30 on 2026-07-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0003_alter_resume_trainee'),
        ('accounts', '0014_alter_customuser_role_alter_traineeprofile_user_and_more'),
        ('applications', '0002_rename_student_to_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='trainees.resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.traineeprofile'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_letter_text',
            field=models.TextField(default='Dear candidate, We are pleased to extend this placement selection offer letter for the selected role parameters. Welcome aboard!', help_text='Full contents of selection offer letter'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.traineeprofile'),
        ),
    ]
