# Generated by Django 4.2.30 on 2026-06-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Job Role Title')),
                ('description', models.TextField(help_text='Detailed description of roles and technical responsibilities')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-time Employment'), ('INTERNSHIP', 'Corporate Internship'), ('CONTRACT', 'Freelance / Contract')], default='FULL_TIME', max_length=20)),
                ('location', models.CharField(default='Bengaluru, IND', max_length=100)),
                ('salary_package', models.CharField(help_text='Estimated annual CTC (e.g. 12 LPA) or monthly stipend', max_length=50)),
                ('skills_required', models.JSONField(default=list, help_text='JSON list of mandatory skills required')),
                ('min_cgpa_required', models.DecimalField(decimal_places=2, default=6.0, help_text='Minimum threshold CGPA score to submit application', max_digits=4)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility in active student student feeds')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.recruiterprofile')),
            ],
        ),
    ]
