# Generated by Django 4.2.30 on 2026-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_course_placementofficerprofile_courses_handled_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_courses',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='accounts.course'),
        ),
    ]
