# Generated by Django 4.2.30 on 2026-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_required_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(blank=True, default=0, help_text='Minimum years of experience required for this job'),
        ),
    ]
