# Generated by Django 6.0.7 on 2026-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_experience_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls visibility in active trainee trainee feeds'),
        ),
    ]
