# Generated by Django 4.2.30 on 2026-06-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_alter_studentprofile_experience_years'),
        ('jobs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Model version identifier (e.g. v2026.06.11)', max_length=50, unique=True)),
                ('algorithm_name', models.CharField(default='RandomForestClassifier', max_length=150)),
                ('accuracy', models.FloatField(help_text='Model overall accuracy score')),
                ('precision', models.FloatField(help_text='Model precision score')),
                ('recall', models.FloatField(help_text='Model recall score')),
                ('f1_score', models.FloatField(help_text='Model F1 score parameter')),
                ('model_file_path', models.CharField(help_text='Absolute or relative path to joblib serialized file', max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, help_text='Path to scaler joblib file if used', max_length=500, null=True)),
                ('features_used', models.JSONField(default=list, help_text='List of feature names input into the model')),
                ('is_active', models.BooleanField(default=False, help_text='Determines if this version is queried on production endpoints')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Voluntary summary notes for model changes', null=True)),
            ],
            options={
                'verbose_name': 'ML Model Metadata',
                'verbose_name_plural': 'ML Model Metadata Logs',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dataset registry label', max_length=250)),
                ('file_upload', models.FileField(blank=True, help_text='Optional CSV data source file', null=True, upload_to='ml_datasets/')),
                ('is_validated', models.BooleanField(default=False, help_text='Dataset structure and format check index')),
                ('rows_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePlacementPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField()),
                ('skills_count', models.IntegerField()),
                ('internships_count', models.IntegerField()),
                ('certifications_count', models.IntegerField()),
                ('aptitude_score', models.IntegerField()),
                ('projects_count', models.IntegerField()),
                ('placement_probability', models.FloatField(help_text='Calculated model trainer probability (0.0 to 1.0)')),
                ('confidence_score', models.FloatField(help_text='Accuracy confidence indices based on feature distribution')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_engine.mlmodelmetadata')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_predictions', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Calculated matching coefficient (0 to 100)')),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('student', 'job')},
            },
        ),
    ]
