# Generated by Django 4.2.30 on 2026-07-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_role_alter_traineeprofile_user_and_more'),
        ('ml_engine', '0002_rename_student_to_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateplacementprediction',
            name='placement_probability',
            field=models.FloatField(help_text='Calculated model placement probability (0.0 to 1.0)'),
        ),
        migrations.AlterField(
            model_name='candidateplacementprediction',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_predictions', to='accounts.traineeprofile'),
        ),
        migrations.AlterField(
            model_name='jobrecommendationcache',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='accounts.traineeprofile'),
        ),
    ]
