# Generated by Django 4.2.30 on 2026-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'College Placement Admin'), ('student', 'Candidate Student'), ('recruiter', 'Corporate Recruiter Partner'), ('placement_officer', 'Placement Officer')], default='student', max_length=30),
        ),
    ]
