# Generated by Django 4.2.30 on 2026-06-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_approval_status_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
