# Generated by Django 4.2.30 on 2026-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_placementofficerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(default='MCA', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='usn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='University Seat Number'),
        ),
    ]
