# Generated by Django 4.2.30 on 2026-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofile_degree_alter_studentprofile_usn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='placementofficerprofile',
            name='courses_handled',
            field=models.ManyToManyField(blank=True, related_name='placement_officers', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='accounts.course'),
        ),
    ]
