# Generated by Django 4.2.30 on 2026-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentprofile_batch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch_timing',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course_edit_request_status',
            field=models.CharField(choices=[('none', 'No Request'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_course_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_status',
            field=models.CharField(choices=[('Training', 'Training'), ('Placement Ready', 'Placement Ready'), ('Placed', 'Placed'), ('Alumni', 'Alumni')], default='Training', max_length=50),
        ),
    ]
