# Generated by Django 4.2.30 on 2026-07-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='usn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Unique Student Number'),
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
