# Generated by Django 4.2.30 on 2026-07-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, verbose_name='Years of Experience'),
        ),
    ]
