# Generated by Django 4.2.30 on 2026-07-11 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_student_to_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'College Placement Admin'), ('trainee', 'Trainee'), ('recruiter', 'Corporate Recruiter Partner'), ('trainer', 'Trainer')], default='trainee', max_length=30),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='usn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Unique Trainee Number'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='courses_handled',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
