# Generated by Django 6.0.7 on 2026-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_role_alter_traineeprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'College Placement Admin'), ('trainee', 'Candidate Student'), ('recruiter', 'Corporate Recruiter Partner'), ('trainer', 'Placement Officer')], default='trainee', max_length=30),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='usn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Unique Student Number'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='courses_handled',
            field=models.ManyToManyField(blank=True, related_name='placement_officers', to='accounts.course'),
        ),
    ]
