# Generated by Django 4.2.30 on 2026-07-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_role_alter_traineeprofile_user_and_more'),
        ('trainees', '0002_rename_student_to_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.traineeprofile'),
        ),
    ]
