# Generated by Django 4.2.30 on 2026-06-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Technical Round 1', max_length=150)),
                ('stage', models.CharField(choices=[('TECHNICAL', 'Technical Evaluation Round'), ('MANAGERIAL', 'Managerial Assessment'), ('HR', 'Human Resources Culture Fit')], default='TECHNICAL', max_length=30)),
                ('scheduled_at', models.DateTimeField(help_text='Time coordinates for candidate slot')),
                ('platform', models.CharField(default='Google Meet', max_length=50)),
                ('meet_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Video Call URL link')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('feedback_notes', models.TextField(blank=True, help_text='Detailed evaluation remarks and performance ratings', null=True)),
                ('rating_score', models.IntegerField(blank=True, help_text='Candidate performance score (1-5)', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
