# Generated by Django 6.0.7 on 2026-07-27 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_role_alter_traineeprofile_courses_and_more'),
        ('applications', '0003_alter_application_resume_alter_application_trainee_and_more'),
        ('interviews', '0001_initial'),
        ('jobs', '0004_alter_job_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('HR', 'HR'), ('MANAGERIAL', 'Managerial')], default='TECHNICAL', max_length=20)),
                ('questions', models.JSONField(default=list, help_text='Stored list of questions generated by AI')),
                ('answers', models.JSONField(default=list, help_text='Stored student answers corresponding to each question')),
                ('technical_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('problem_solving_score', models.IntegerField(default=0)),
                ('resume_score', models.IntegerField(default=0)),
                ('placement_prediction', models.FloatField(default=0.0)),
                ('interview_readiness_score', models.IntegerField(default=0)),
                ('feedback', models.JSONField(default=dict, help_text='Detailed feedback: Strengths, Weaknesses, Areas to Improve, Recommended Learning Topics')),
                ('skill_gap', models.JSONField(default=dict, help_text='Compare matching and missing skills')),
                ('recommended_skills', models.JSONField(default=list, help_text='Recommended courses and practice tasks')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_readiness_records', to='applications.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_readiness_records', to='jobs.job')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_readiness_records', to='accounts.traineeprofile')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
