# Generated by Django 4.2.30 on 2026-06-24 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('JOB_ALERT', 'New Active Job Post'), ('STUDENT_APPLIED', 'Candidate Submitted Registration'), ('INTERVIEW_INVITATION', 'Interview Invitation Scheduling'), ('STATUS_UPDATE', 'Application Pipeline Shift'), ('ADMIN_BROADCAST', 'General Campus Announcement')], default='STATUS_UPDATE', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
